#!/usr/bin/env bash

go mod tidy

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "Go mod is out of date!"
  exit 1
fi

for d in pkg/* ; do
  pushd "$d" || exit
    go fmt .
  popd || exit
done

go fmt main.go

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "bad go formatting!"
  exit 1
fi

docker build --no-cache .
