name: push image

on:
  push:
    branches:
      - master

jobs:
  push-image:
    name: push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tasmota-watcher:master-head .
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tasmota-watcher:master-head